
# Input arguments
inputpdbfile=$1
n=$2

# Data proccessing
./dssp $inputpdbfile dssp_temp 2> /dev/null
./sequences.pl prot_$n > temp_seq 2> /dev/null
grep "^[^>]" temp_seq | ./surface.pl > temp_surf prot_$n 2> /dev/null
pymol $inputpdbfile protein.pml -g output_$n.png -c > /dev/null

# Showing the results
#open output_$n.png

echo "<html><head><title>Report for Protein $n</title></head>" > report_$n.html
echo "<body><div width='600px'>" >> report_$n.html
echo "<p></p><p align='center'><img src='output_$n.png'></p>" >> report_$n.html
echo "<p>" >> report_$n.html

echo "<h2>Sequence:</h2><hr>" >> report_$n.html
cat temp_seq >> report_$n.html
echo "<h2>Surface report:</h2><hr>" >> report_$n.html
cat temp_surf >> report_$n.html

echo "<br><hr />" >> report_$n.html
echo "<p align='center'>&copy; 2012 | Report generated by <a href='http://www.hectorvalverde.com/'>hectorvalverde.com</a> laboratory</p>" >> report_$n.html
echo "<div></body></html>" >> report_$n.html

#cat report_$n.html

# Cleaing temporal data
#rm dssp_temp
#rm temp_seq
#rm temp_surf

